name: Dependabot Changelog Entry

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches: [main]

permissions: read-all

jobs:
  changelog:
    name: Changelog
    if: contains(github.event.pull_request.labels.*.name, 'dependabot/changelog')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - uses: octo-sts/action@210248e8ae1ae1550aa6e232c6f192b3ccbf7335
        id: sts
        with:
          scope: ${{ github.repository}}
          identity: actions-pr
      - name: Changelog
        uses: crambl/dependabot-changelog-writer@f3da7ee89d2902ec52a5872bdf7b71342dd7bd8b # v1.1.2
        with:
          push-token: ${{ steps.sts.outputs.token }}
          commit-message: "chore: Update changelog for Dependabot"
          changelog: ./CHANGELOG.md
          section-header: "Changed"
          changelog-entry-pattern: "Update [dep] from `[old]` to `[new]`. ([pr-link]) _@dependabot_"
          push-changes: true
