name: Dependabot Changelog Entry

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches: [main]

permissions: read-all

jobs:
  workflow:
    name: Workflow
    uses: ./.github/workflows/dependabot-changelog.yaml
    permissions:
      contents: read
      id-token: write
