name: Dependabot PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  workflow:
    name: Workflow
    uses: ./.github/workflows/dependabot-pr.yaml
    permissions:
      contents: write
