name: Publish Release

on:
  workflow_call:
    inputs:
      changelog_path:
        description: Path to the CHANGELOG file; this needs to follow the Keep a Changelog pattern.
        type: string
        required: false
        default: ./CHANGELOG.md
      version:
        description: The version to be released.
        type: string
        required: false
        default: ${{ github.ref_name }}
      make_latest:
        description: Whether to make the release the latest release.
        type: boolean
        required: false
        default: true
      artifacts:
        description: Comma separated list of artifact path to be uploaded to the release; this supports globs.
        type: string
        required: false
        default: ""

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 1

      - name: Get changelog entry
        id: changelog
        uses: mindsers/changelog-reader-action@1faaf50aa09d5793d9a100819973df801febfb31 # v2.4.0
        with:
          path: ${{ inputs.changelog_path }}
          version: ${{ inputs.version }}

      - name: Release notes
        id: release_notes
        run: |
          set -euo pipefail

          changes="$(
          cat <<'EOF'
          ${{ steps.changelog.outputs.changes }}
          EOF
          )"

          changelog="$(echo "${changes}" | sed -r 's/\[(@[^]]+)\]\([^)]+\)/\1/g')"

          {
            echo "changelog<<EOF"
            echo "${changelog}"
            echo "EOF"
          } >> "${GITHUB_OUTPUT}"

      - name: Create release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          token: ${{ github.token }}
          makeLatest: ${{ inputs.make_latest }}
          allowUpdates: true
          body: ${{ steps.release_notes.outputs.changelog }}
          artifacts: ${{ inputs.artifacts }}
