name: GH Reusable Workflow Publish Release

on:
  workflow_call:
    inputs:
      changelog_path:
        description: Path to the CHANGELOG file; this needs to follow the Keep a Changelog pattern.
        type: string
        required: false
        default: ./CHANGELOG.md
      version:
        description: The version to be released.
        type: string
        required: false
        default: ${{ github.ref_name }}
      make_latest:
        description: Whether to make the release the latest release.
        type: boolean
        required: false
        default: true
      artifacts:
        description: Comma seperated list of artifact path to be uploaded to the release; this supports globs.
        type: string
        required: false
        default: ""

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 1

      - name: Get changelog entry
        id: changelog
        uses: mindsers/changelog-reader-action@32aa5b4c155d76c94e4ec883a223c947b2f02656 # v2.2.3
        with:
          path: ${{ inputs.changelog_path }}
          version: ${{ inputs.version }}

      - name: Create release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          token: ${{ github.token }}
          makeLatest: ${{ inputs.make_latest }}
          allowUpdates: true
          body: ${{ steps.changelog.outputs.changes }}
          artifacts: ${{ inputs.artifacts }}
