name: GH Reusable Workflow Publish Release

on:
  workflow_call:
    inputs:
      changelog_path:
        description: Path to the CHANGELOG file; this needs to follow the Keep a Changelog pattern.
        type: string
        required: false
        default: ./CHANGELOG.md
      version:
        description: The version to be released.
        type: string
        required: false
        default: ${{ github.ref_name }}
      make_latest:
        description: Whether to make the release the latest release.
        type: boolean
        required: false
        default: true
      body:
        description: The release body.
        type: string
        required: false
        default: ""
      release_notes_mode:
        description: The release notes mode; can be one of none, changelog or commits.
        type: string
        required: false
        default: none
      artifacts:
        description: New line separated list of artifact path to be uploaded to the release; this supports globs.
        type: string
        required: false
        default: ""

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Get changelog entry
        if: ${{ inputs.release_notes_mode == 'changelog' }}
        id: changelog
        uses: mindsers/changelog-reader-action@32aa5b4c155d76c94e4ec883a223c947b2f02656 # v2.2.3
        with:
          path: ${{ inputs.changelog_path }}
          version: ${{ inputs.version }}

      - name: Configure
        id: configure
        run: |
          set -euo pipefail

          body_file="$(mktemp)"

          cat <<EOF > "${body_file}"
          ${{ inputs.body }}
          EOF

          if [[ "${{ inputs.release_notes_mode }}" == "changelog" ]]; then
            printf '## What's Changed\n\n' >> "${body_file}"

            changes="$(cat <<EOF
          ${{ steps.changelog.outputs.changes }}
          EOF
          )"

            sed -r 's/\[(@[^]]+)\]\([^)]+\)/\1/g' <<< "${changes}" >> "${body_file}"
          fi

          {
            echo "body_path=${body_file}"
          } >> "${GITHUB_OUTPUT}"

      - name: Create release
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048 # v2.2.0
        with:
          token: ${{ github.token }}
          make_latest: ${{ inputs.make_latest }}
          files: ${{ inputs.artifacts }}
          body_path: ${{ steps.configure.outputs.body_path }}
          generate_release_notes: ${{ inputs.release_notes_mode == 'commits' }}
