name: Validate GitHub Workflows

on:
  workflow_call:
    inputs:
      auto_doc:
        description: If auto-doc should be run.
        type: boolean
        required: false
        default: false
      auto_doc_script:
        description: The script to run auto-doc.
        type: string
        required: false
      shellcheck:
        description: If shellcheck should be run.
        type: boolean
        required: false
        default: false
      yamlfmt:
        description: If yamlfmt should be run.
        type: boolean
        required: false
        default: false
      rumdl:
        description: If rumdl should be run.
        type: boolean
        required: false
        default: false
      markdownlint:
        description: DEPRECATED - If markdownlint should be run.
        type: boolean
        required: false
        default: false

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install ghactl
        uses: action-stars/ghactl-action@c556c5f2cfcb1f6643bdecf1bf601c706954a37a # v0.0.1
        with:
          token: ${{ github.token }}
          version: latest

      - name: Install tools
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail

          ghactl tool install --owner rhysd --repo actionlint --version latest
          ghactl tool install --owner tj-actions --repo auto-doc --version latest
          ghactl tool install --owner google --repo yamlfmt --version latest

      - name: Run actionlint
        run: actionlint -shellcheck=shellcheck

      - name: Run auto-doc check
        if: inputs.auto_doc
        run: |
          set -euo pipefail

          auto_doc_script="${{ inputs.auto_doc_script }}"

          if [[ -n "${auto_doc_script}" ]]; then
            ${auto_doc_script}
          else
            find ./.github/workflows -maxdepth 1 -name '*.yaml' ! -name '_*' -print0 | while read -r -d $'\0' file; do
              name="$(basename "${file}" .yaml)"

              tmp_readme="$(mktemp)"
              printf '## Secrets\n\n## Inputs\n\n## Outputs' >"${tmp_readme}"
              auto-doc --colMaxWords 100 --repository ${{ github.repository }} --reusable --reusableOutputColumns "Output" --reusableOutputColumns "Description" --filename "${file}" --output "${tmp_readme}"
              sed -i 's/## /### /g' "${tmp_readme}"
              sed -i 's/||/\\|\\|/g' "${tmp_readme}"
              sed -i 's/"\\|"/\\|/g' "${tmp_readme}"

              sed -i -e "/MERGE:START:${name}/,/MERGE:END:${name}/c\<!-- MERGE:START:${name} - Do not remove or modify this section -->\n\n<!-- MERGE:END:${name} - Do not remove or modify this section -->" ./README.md
              sed -i "/MERGE:START:${name}/r ${tmp_readme}" ./README.md

              rm -f "${tmp_readme}"
            done
          fi

          if [[ -n "$(git status --porcelain --untracked-files=no)" ]]
          then
            echo "Documentation not up to date; please run auto-doc and commit changes!" >&2
            exit 1
          fi

      - name: Run yamlfmt check
        if: inputs.yamlfmt
        run: |
          set -euo pipefail

          yamlfmt -lint .

      - name: Run shellcheck
        if: inputs.shellcheck
        run: |
          set -euo pipefail

          # shellcheck disable=SC2038
          find . -type f -name "*.sh" | xargs --no-run-if-empty -n1 shellcheck

      - name: Run markdownlint check
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        if: inputs.markdownlint
